### ISSUE TITLE
uninitialized constant SheetsExtension::MenuRenderer

### ISSUE THREAD

**Issue by fanta** [radiant/radiant-sheets-extension#11]
I don't know if this issue belongs to this project or if it belongs to radiant, but when I run:

gem install radiant --prerelease

it installs radiant 1.0.0.rc3 and radiant-sheets-extension 1.0.4

and running:

rake db:bootstrap

throws this error: 

uninitialized constant SheetsExtension::MenuRenderer

on this commit 45952c4 is the line that is throwing that error

**Comment by ryanjm** [comment]
I'm having this same issue. I'm running ruby 1.9.2p180 and Radiant 1.0.0.rc3.

Any work arounds?

**Comment by ryanjm** [comment]
I just cloned Radiant and then linked to it in my gemfile:

```
gem 'radiant', :path => '../radiant/'
```

This allowed me to run `bundle exec rake production db:bootstrap` but then the server doesn't work (can't find pages).

**Comment by ghost** [comment]
@fanta, @ryanjm - right now gems released to work with 1.x are (i think) mostly targeting compatibility with radiant/master. at least that is what's happening here. the menu renderer is newer than rc3 and sheets has been updated accordingly. you can add `gem "radiant", :git => "git://github.com/radiant/radiant.git"` to your gemfile then `bundle update` to use radiant/master instead of rc3.

@ryanjm - did you start the server in production mode?

**Comment by ryanjm** [comment]
Thanks for pointing that out. I was doing `script/server production` when I needed `script/server -e production`.

**Comment by fanta** [comment]
Got it, thank you, I'll close the issue
